# Generated by Django 3.1.6 on 2021-04-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210419_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sections',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
