# Generated by Django 3.1.6 on 2021-04-24 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsection',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ps', to='api.project'),
        ),
    ]
