# Generated by Django 3.1.6 on 2021-05-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubproject',
            name='account',
        ),
        migrations.DeleteModel(
            name='Commit',
        ),
        migrations.DeleteModel(
            name='GithubProject',
        ),
    ]
